namespace PlanesRemake.Runtime.Sound
{
	public class ClipIds
	{
		// This file is auto generated from the ClipsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		public const string COIN_CLIP = "CoinClip";
		public const string MUSIC_CLIP = "MusicClip";
		public const string BUTTON_CLICK_CLIP = "ButtonClickClip";
		public const string AIRCRAFT_ENGINE_CLIP = "AircraftEngineClip";
		public const string AIRCRAFT_EXPLOSION_CLIP = "AircraftExplosionClip";
	}
}

