namespace PlanesRemake.Runtime.Localization
{
	public class LanguageIds
	{
		// This file is auto generated from the ViewsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		public const string EN = "En";
		public const string ES = "Es";
		public const string FR = "Fr";
	}
}

