namespace PlanesRemake.Runtime.Gameplay
{
	public class AircraftIds
	{
		// This file is auto generated from the ViewsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		public const string PLANE = "Plane";
		public const string ICE_BLADES = "IceBlades";
		public const string SPACESHIP = "Spaceship";
		public const string BLUE_BULL = "BlueBull";
	}
}

