namespace PlanesRemake.Runtime.Gameplay
{
	public class AircraftIds
	{
		// This file is auto generated from the ViewsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		public const string PLANE = "Plane";
	}
}

