namespace PlanesRemake.Runtime.UI.Views
{
	public class ViewIds
	{
		// This file is auto generated from the ViewsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		public const string MAIN_MENU = "MainMenu";
		public const string HUD = "Hud";
		public const string PAUSE_MENU = "PauseMenu";
		public const string TOUCH_CONTROLS = "TouchControls";
		public const string OPTIONS_MENU = "OptionsMenu";
		public const string AIRCRAFT_SHOWCASE = "AircraftShowcase";
	}
}

